
' Lite Process Monitor


Option Strict On

Imports Common.Misc


Public Class frmGlobalReport

    Private Sub cmdCancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdCancel.Click
        Me.Close()
    End Sub

    Private Sub cmdSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdSave.Click
        _frmMain.saveDial.Filter = "Text file (*.txt)|*.txt"
        _frmMain.saveDial.Title = "Save report"
        If _frmMain.saveDial.ShowDialog = Windows.Forms.DialogResult.OK Then
            Call saveReport(_frmMain.saveDial.FileName)
        End If
    End Sub

    ' Change caption
    Private Sub setCaption(ByVal s As String)
        Me.lblState.Text = s
        'Dim x As Integer = CInt((pgb.Width - Me.pgb.CreateGraphics.MeasureString(s, Me.Font).Width) / 2)
        'Dim y As Integer = CInt((pgb.Height - Me.pgb.CreateGraphics.MeasureString(s, Me.Font).Height) / 2)
        'Me.pgb.CreateGraphics.DrawString(s, Me.Font, Brushes.Black, x, y)
        Application.DoEvents()
    End Sub

    ' Save global report
    Public Sub saveReport(ByVal _fileToSave As String)

        ' Services
        ' Handles
        ' Windows
        ' Threads
        ' General
        ' Modules
        ' Memory regions

        Dim _test As Integer = Native.Api.Win32.GetElapsedTime
        Using stream As New System.IO.StreamWriter(_fileToSave, False)

            ' The goal is to retrieve all informations before saving it
            Dim _dicoServices As New Dictionary(Of String, cService)
            Dim _dicoProcesses As New Dictionary(Of Integer, cProcess)


            ' == Write general informations to log
            setCaption("Writing header to report...")
            stream.WriteLine("Report generated by Lite Process Monitor")
            stream.WriteLine("File version : " & My.Application.Info.Version.ToString)
            stream.WriteLine(Date.Now.ToLongDateString & " -- " & Date.Now.ToLongTimeString)
            stream.WriteLine()
            stream.WriteLine()
            stream.WriteLine()


            ' == Write informations about system


            ' == Write services informations
            If Me.chkServices.Checked Then
                setCaption("Writing services list to report...")
                stream.WriteLine("====")
                stream.WriteLine("==      Running services      ==")
                stream.WriteLine("====")
                stream.WriteLine()
                stream.WriteLine(_dicoServices.Count.ToString & " services running")
                stream.WriteLine()
                For Each it As cService In _dicoServices.Values
                    stream.WriteLine("--------------------------------")
                    stream.WriteLine("Service name : " & it.Infos.Name)
                    stream.WriteLine("--------------------------------")
                    For Each s As String In serviceInfos.GetAvailableProperties
                        stream.WriteLine(s & " : " & it.GetInformation(s))
                    Next
                    stream.WriteLine()
                Next
                stream.WriteLine()
                stream.WriteLine()
                stream.WriteLine()
            End If


            ' == Write informations about processes
            setCaption("Writing processes infos to report...")
            stream.WriteLine("====")
            stream.WriteLine("==      Running processes     ==")
            stream.WriteLine("====")
            stream.WriteLine()
            stream.WriteLine(_dicoProcesses.Count.ToString & " processes running")
            stream.WriteLine()
            Me.pgb.Maximum = _dicoProcesses.Count

            stream.WriteLine()

            stream.Close()
        End Using

        _test = Native.Api.Win32.GetElapsedTime - _test
        setCaption("Done in " & _test.ToString & " ms")

        Misc.ShowMsg("System report", "Saved report successfully.", MessageBoxButtons.OK)

    End Sub

    Private Sub frmGlobalReport_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        CloseWithEchapKey(Me)

        SetToolTip(Me.chkAllHandles, "Get all handles (including unnamed handles)")
        SetToolTip(Me.chkAllWindows, "Get all windows (including unnamed windows)")
        SetToolTip(Me.chkFull, "Write a complet report, with all informations availables. You should NOT use this option because report file can be up to 100MB")
        SetToolTip(Me.chkHandles, "Write handles infos")
        SetToolTip(Me.chkMemory, "Write memory regions infos")
        SetToolTip(Me.chkModules, "Write modules infos")
        SetToolTip(Me.chkServices, "Write services infos")
        SetToolTip(Me.chkThreads, "Write threads infos")
        SetToolTip(Me.chkWindows, "Write windows infos")
        SetToolTip(Me.cmdCancel, "Cancel")
        SetToolTip(Me.cmdSave, "Save report as a text file")
    End Sub
End Class